/**
 * Author: Vidush H. Namah (2019)
 * 
 * Centralized location for all Action keys
 */

export const SAGA_FETCH_FEATURED_DATA = "SAGA_FETCH_FEATURED_DATA";
export const SAGA_FETCH_FEATURED_START = "SAGA_FETCH_FEATURED_START";
export const SAGA_FETCH_FEATURED_SUCCESS = "SAGA_FETCH_FEATURED_SUCCESS";
export const SAGA_FETCH_FEATURED_FAILED = "SAGA_FETCH_FEATURED_FAILED";


export const SAGA_FETCH_PLAYLIST_DATA = "SAGA_FETCH_PLAYLIST_DATA";
export const SAGA_FETCH_PLAYLIST_START = "SAGA_FETCH_PLAYLIST_START";
export const SAGA_FETCH_PLAYLIST_SUCCESS = "SAGA_FETCH_PLAYLIST_SUCCESS";
export const SAGA_FETCH_PLAYLIST_FAILED = "SAGA_FETCH_PLAYLIST_FAILED";